default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bank_accounting_development
  username: postgres
  password: postgres

test:
  <<: *default
  database: bank_accounting_test
  username: postgres
  password: postgres

production:
  <<: *default
  database: api_production
  username: api
  password: <%= ENV['API_DATABASE_PASSWORD'] %>
